########################PLUGIN CONFIGURATION########################

max_homes: 3 #Maximum amount of homes a player can have (Default: 3) (-1 = unlimited)
language: spanish #Language of the plugin
#Available languages:
#- english
#- spanish

allow_welcome_message: false #Allow welcome message
allow_enabled_message: true #Allow plugin enabled message
allow_default_welcome_message: true #Allow default welcome message

english:
    welcome_message: "Welcome to the server!" #Welcome message
    enabled_message: "The plugin has been enabled!" #Plugin enabled message
    max_homes_message: "You have reached the maximum amount of homes!" #Max homes message
    home_set_message: "Home %name% created!" #Home set message

spanish:
    welcome_message: "Bienvenido al servidor!" #Welcome message
    enabled_message: "El plugin ha sido activado!" #Plugin enabled message
    max_homes_message: "Has alcanzado el numero máximo de homes!" #Max homes message
    home_set_message: "Home %name% creada!" #Home set message

#####################HERE THE HOMES ARE SAVED#######################

#Example of how homes are saved
player_name:
    home_name:
      #==: org.bukkit.Location
      world: mundo
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0
      pitch: 0.0